apiVersion: apps/v1
kind: Deployment
metadata:
  name: oculus-deployment
  labels:
    app: oculus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oculus
  template:
    metadata:
      labels:
        app: oculus
    spec:
      containers:
      - name: oculus
        image: verticleio/oculus:latest
        ports:
        - containerPort: 8080